os: linux

dist: bionic

language: python

jobs:
  include:
    - stage: checks 
      python: 3.8
      env: TOXENV=flakes

    - stage: tests
      python: 3.8
      env: TOXENV=py38-dj30

    - python: 3.8
      env: TOXENV=py38-dj22

    - python: 3.7
      env: TOXENV=py37-dj30

    - python: 3.7
      env: TOXENV=py37-dj22

    - python: 3.6
      env: TOXENV=py36-dj30

    - python: 3.6
      env: TOXENV=py36-dj22

    - python: 3.5
      env: TOXENV=py36-dj22

    - stage: packaging
      python: 3.8
      env: TOXENV=twine


install:
  - pip install tox
  - pip install coveralls

script:
  tox

after_success:
  - coveralls
